### ISSUE TITLE
[Request]: Add extensions version number in the report

### ISSUE THREAD

**Issue by Turborwx** [asheroto/Extension-Exporter#1]
### Describe the feature or improvement you're requesting

Hello this is a very useful extension but I would like to ask if it could be possible to add each extension version number next to their name in the HTML report file?

For example in the current demostration video the report file would print this:

```
ENABLED EXTENSIONS
Extension Exporter 1.0.0
Google Translate 2.0.13

DISABLED EXTENSIONS
Scientific Calculator 1.5.4
```

Thanks

**Comment by asheroto** [comment]
Hey, this is a great idea! I'll work on it and update the issue later.

**Comment by asheroto** [comment]
I have submitted the updated version `1.2.0` to the Chrome web store. Usually it takes a few days for approval. Thanks for the idea!

![image](https://github.com/asheroto/Extension-Exporter/assets/49938263/18bdf8c2-a083-430d-8210-c4f46620c16c)
