### ISSUE TITLE
[Request]: EDGE Store Links in HTML

### ISSUE THREAD

**Issue by pantantrollo** [asheroto/Extension-Exporter#3]
### Describe the feature or improvement you're requesting

Hello good,

I imagine that ordinally the extension was made for the Chrome browser and that is why all the links that are saved in the HTML file refer only to the Google store.

The fact is that on EDGE it works just as well, except that even having the extensions from the MS Edge store, the HTML file generated assumes that they are from the Google store, with the consequent error of not found.

It would be nice if the links refer to the store where the extensions have been installed

Thank you very much for the extension
All the best

**Comment by asheroto** [comment]
I tried getting this to work on Edge about a year ago, but kept running into issues. Have you tested the extension and confirmed everything works, links included? I might just need to help testing this out.

You can load the CRX file into Edge or the unpacked version from the repo files.

**Comment by pantantrollo** [comment]
Hello good,
Sorry, my English is very bad, I translate with Google Translate :-)

I have created a new profile in EDGE, installed the extension from the GitHub repository, the latest version, 2.0, without problems, and the extension works well exporting the .html file, so far everything is ok.

I have installed several extensions from the MS EDGE store, and this is where the extension no longer does what it should do, and that is direct the links to the MS EDGE store, instead, it does so to the Google store, with the consequent 404 error, for not finding the corresponding extension, which is logical because the same extension in different stores has different IDs

I paste part of the text from the .html of the page that is created, you will see that all the links point to the Google store, not the Microsoft store.

<ol class="enabled">
        <li><a href="https://chrome.google.com/webstore/detail/dpaelbjipneennmjbjmgkdlbajncmbmj" target="_blank" title="2FAS Browser Extension is simple, private, and secure: 1 click, 1 tap, and your token is automatically entered!">2FAS - Two Factor Authentication 1.7.0</a> <a href="https://clients2.google.com/service/update2/crx?response=redirect&prodversion=49.0&acceptformat=crx3&x=id%3Ddpaelbjipneennmjbjmgkdlbajncmbmj%26installsource%3Dondemand%26uc" target="_blank" title="Download CRX file" alt="Download CRX file"><span class="crx-icon"></span></a></li>
            <li><a href="https://chrome.google.com/webstore/detail/hfjadhjooeceemgojogkhlppanjkbobc" target="_blank" title="Mejora al instante tus textos con el revisor de gramática de LanguageTool y su opción de parafrasear oraciones.">Corrector ortográfico y gramatical - LanguageTool 8.10.4</a> <a href="https://clients2.google.com/service/update2/crx?response=redirect&prodversion=49.0&acceptformat=crx3&x=id%3Dhfjadhjooeceemgojogkhlppanjkbobc%26installsource%3Dondemand%26uc" target="_blank" title="Download CRX file" alt="Download CRX file"><span class="crx-icon"></span></a></li>
            <li><a href="https://chrome.google.com/webstore/detail/doikmfpjbcjjimnbablebijofdbgfepb" target="_blank" title="Export name and URL of all installed extensions into an HTML file.">Extension Exporter 2.0.0</a> <a href="https://clients2.google.com/service/update2/crx?response=redirect&prodversion=49.0&acceptformat=crx3&x=id%3Ddoikmfpjbcjjimnbablebijofdbgfepb%26installsource%3Dondemand%26uc" target="_blank" title="Download CRX file" alt="Download CRX file"><span class="crx-icon"></span></a></li>
            <li><a href="https://chrome.google.com/webstore/detail/bhahgfgngfghgjhnpplmemebhenieijb" target="_blank" title="Manage extensions, Quickly enable/disable, Support batching operation, Smart sorting. Fast, Simple and Secure.">Extension Manager 9.5.1</a> <a href="https://clients2.google.com/service/update2/crx?response=redirect&prodversion=49.0&acceptformat=crx3&x=id%3Dbhahgfgngfghgjhnpplmemebhenieijb%26installsource%3Dondemand%26uc" target="_blank" title="Download CRX file" alt="Download CRX file"><span class="crx-icon"></span></a></li>
            <li><a href="https://chrome.google.com/webstore/detail/jgcmbjdhakghmngjkdpejdcchbigdmgf" target="_blank" title="Automatically group tabs, save tabs/groups, and provide shortcuts for tabs/groups.">Tab Groups Extension 1.0.9</a> <a href="https://clients2.google.com/service/update2/crx?response=redirect&prodversion=49.0&acceptformat=crx3&x=id%3Djgcmbjdhakghmngjkdpejdcchbigdmgf%26installsource%3Dondemand%26uc" target="_blank" title="Download CRX file" alt="Download CRX file"><span class="crx-icon"></span></a></li>
            <li><a href="https://chrome.google.com/webstore/detail/odfafepnkmbhccpbejgmiehpchacaeak" target="_blank" title="Por fin, un bloqueador eficiente con uso mínimo de procesador y memoria.">uBlock Origin 1.57.2</a> <a href="https://clients2.google.com/service/update2/crx?response=redirect&prodversion=49.0&acceptformat=crx3&x=id%3Dodfafepnkmbhccpbejgmiehpchacaeak%26installsource%3Dondemand%26uc" target="_blank" title="Download CRX file" alt="Download CRX file"><span class="crx-icon"></span></a></li>
    </ol>


All the best

**Comment by asheroto** [comment]
Thanks for the info. I'm working on this and am just about done. Should have an update today I believe.

**Comment by asheroto** [comment]
Support has been added for Edge in v3. I have published it to the Chrome Web Store and Edge Add-ons, just awaiting approval.

https://github.com/asheroto/Extension-Exporter/releases/tag/3.0.0

**Comment by pantantrollo** [comment]
Perfect 
What I've seen so far works very well.

Thank you so much
